export const portfolio = [
  {
    projet: 'Formaceo',
    img: './assets/projects/formaceo.jpg',
    job: "Creation de tous les modules sauf vidéo. Mise a jour des modules existants, design de la base de donnée et ccreation des tables. Creation des lambdas inerantes aux fonctionnement des modules et de la recuperation des datas du cognito d'AWS.",
    techs: ['Python', 'Ionic', 'Typescript', 'react', 'sass', 'aws'],
    type: ['web', 'App'],
    link: 'https://main.d9p26hu11c7dg.amplifyapp.com/page/Home',
  },
  {
    projet: 'Deliceo',
    img: './assets/projects/deliceo.png',
    job: "Creation de tous les modules sauf vidéo. Mise a jour des modules existants, design de la base de donnée et ccreation des tables. Creation des lambdas inerantes aux fonctionnement des modules et de la recuperation des datas du cognito d'AWS.",
    techs: ['Python', 'Ionic', 'Typescript', 'react', 'sass', 'aws'],
    type: ['web', 'App'],
    link: 'https://main.d3kb9v59slzd6u.amplifyapp.com',
  },
  {
    projet: 'slack',
    img: './assets/projects/slack.jpg',
    job: 'Project de clone',
    techs: ['react', 'css', 'javascript', 'firebase'],
    type: ['web'],
    link: 'https://slack-clone-6f378.web.app',
  },
  {
    projet: 'discord',
    img: './assets/projects/discord.jpg',
    job: 'Project de clone',
    techs: ['react', 'css', 'javascript', 'firebase'],
    type: ['web'],
    link: 'https://discord-app-clone-543e0.web.app',
  },
  {
    projet: 'Netflix',
    img: './assets/projects/netflix.png',
    job: 'Project de clone',
    techs: ['react', 'css', 'javascript'],
    type: ['web'],
    link: 'https://neflix-app-clone.web.app',
  },
  {
    projet: 'Spotify',
    img: './assets/projects/spotify.png',
    job: 'Project de clone',
    techs: ['React', 'redux', 'css', 'firebase'],
    type: ['web'],
    link: 'https://spotify-app-clone-6b635.web.app/#',
  },
  {
    projet: 'AirBnb',
    img: './assets/projects/airbnb.jpg',
    job: 'Project de clone',
    techs: ['React', 'css'],
    type: ['web'],
    link: 'https://airbnb-clone-3e58d.web.app',
  },
  {
    projet: 'Hulu',
    img: './assets/projects/hulu.png',
    job: 'Project de clone',
    techs: ['React', 'css'],
    type: ['web'],
    link: 'https://hulu-clone-13176.web.app',
  },
];
